CREATE TABLE IF NOT EXISTS USEREMPLOYEE (
    ID VARCHAR(255) PRIMARY KEY,
    LOGIN VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
	SALARY NUMERIC(11,4) NOT NULL,
	STARTDATE DATE NOT NULL
);

ALTER TABLE USEREMPLOYEE ADD UNIQUE (login);